apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpz-platform
  name: cpz-platform
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpz-platform
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cpz-platform

    spec:
      imagePullSecrets:
        - name: cpz-registry
      containers:
        - image: registry.digitalocean.com/cpz/cpz-platform:latest
          imagePullPolicy: Always
          name: cpz-platform
          env:
            - name: TRANSPORTER
              value: nats://nats:4222
            - name: PROXY_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PROXY_ENDPOINT
            - name: PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PG_DBNAME
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PG_USER
            - name: PG_PWD
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PG_PWD
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PG_HOST
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PG_PORT
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: REDIS_PASSWORD
            - name: REDIS_TLS
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: REDIS_TLS
            - name: CODE_FILES_LOCATION
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: CODE_FILES_LOCATION
            - name: ENCRYPTION_PWD
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: ENCRYPTION_PWD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: JWT_SECRET
            - name: JWT_TOKEN_EXPIRES
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: JWT_TOKEN_EXPIRES
            - name: REFRESH_TOKEN_EXPIRES
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: REFRESH_TOKEN_EXPIRES
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: MAILGUN_API_KEY
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: MAILGUN_DOMAIN
            - name: LOGDNA_KEY
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: LOGDNA_KEY
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: BOT_TOKEN
            - name: BOT_HOST
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: BOT_HOST
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: NODE_ENV
            - name: CPZ_ENV
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: CPZ_ENV
            - name: NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: NAMESPACE
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: cpz-env
                  key: PORT
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"
