version: "3"
services:
  cpz-eventslogger:
    container_name: cpz-eventslogger
    build:
      context: .
      dockerfile: CPZEventslogger.Dockerfile
    ports:
      - "8101:80"
    environment:
      - FUNCTIONS_WORKER_RUNTIME
      - AzureWebJobsStorage
      - AZ_STORAGE_EVENT_CS
      - AZ_STORAGE_MARKET_CS
      - EG_EMULATOR_MODE
      - LOG_TABLE_STORAGE
      - LOG_POSTGRE
      - DB_API_ENDPOINT
      - DB_API_ACCESS_KEY
      - API_KEY
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
  cpz-marketwatcher:
    container_name: cpz-marketwatcher
    build:
      context: .
      dockerfile: CPZMarketwatcher.Dockerfile
    ports:
      - "8102:80"
    environment:
      - AzureWebJobsStorage
      - AZ_STORAGE_MARKET_CS
      - API_KEY
      - PROXY_ENDPOINT
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - EG_TICKS_ENDPOINT
      - EG_TICKS_KEY
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-candlebatcher:
    container_name: cpz-candlebatcher
    build:
      context: .
      dockerfile: CPZCandlebatcher.Dockerfile
    ports:
      - "8103:80"
    environment:
      - FUNCTIONS_WORKER_RUNTIME
      - AzureWebJobsStorage
      - AZ_STORAGE_MARKET_CS
      - API_KEY
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - EG_CANDLES_ENDPOINT
      - EG_CANDLES_KEY
      - DB_API_ENDPOINT
      - DB_API_ACCESS_KEY
      - CONNECTOR_API_ENDPOINT
      - CONNECTOR_API_KEY
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-adviser:
    container_name: cpz-adviser
    build:
      context: .
      dockerfile: CPZAdviser.Dockerfile
    ports:
      - "8104:80"
    environment:
      - FUNCTIONS_WORKER_RUNTIME
      - AzureWebJobsStorage
      - AZ_STORAGE_TRADE_CS
      - AZ_STORAGE_MARKET_CS
      - API_KEY
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - EG_SIGNALS_ENDPOINT
      - EG_SIGNALS_KEY
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-importer:
    container_name: cpz-importer
    build:
      context: .
      dockerfile: CPZImporter.Dockerfile
    ports:
      - "8105:80"
    environment:
      - AzureWebJobsStorage
      - AZ_STORAGE_MARKET_CS
      - API_KEY
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - DB_API_ENDPOINT
      - DB_API_ACCESS_KEY
      - CONNECTOR_API_ENDPOINT
      - CONNECTOR_API_KEY
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-trader:
    container_name: cpz-trader
    build:
      context: .
      dockerfile: CPZTrader.Dockerfile
    ports:
      - "8106:80"
    environment:
      - FUNCTIONS_WORKER_RUNTIME
      - AzureWebJobsStorage
      - AZ_STORAGE_MARKET_CS
      - AZ_STORAGE_TRADE_CS
      - API_KEY
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - EG_TRADES_ENDPOINT
      - EG_TRADES_KEY
      - CONNECTOR_API_ENDPOINT
      - CONNECTOR_API_KEY
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-control:
    container_name: cpz-control
    build:
      context: .
      dockerfile: CPZControlAPI.Dockerfile
    ports:
      - "8107:80"
    environment:
      - FUNCTIONS_WORKER_RUNTIME
      - AzureWebJobsStorage
      - AZ_STORAGE_CONTROL_CS
      - AZ_STORAGE_MARKET_CS
      - AZ_STORAGE_TRADE_CS
      - AZ_STORAGE_BACKTESTER_CS
      - API_KEY
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - DB_API_ENDPOINT
      - DB_API_ACCESS_KEY
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-backtester:
    container_name: cpz-backtester
    build:
      context: .
      dockerfile: CPZBacktester.Dockerfile
    ports:
      - "8108:80"
    environment:
      - AzureWebJobsStorage
      - AZ_STORAGE_MARKET_CS
      - AZ_STORAGE_TRADE_CS
      - AZ_STORAGE_BACKTESTER_CS
      - API_KEY
      - EG_TASKS_ENDPOINT
      - EG_TASKS_KEY
      - EG_LOG_ENDPOINT
      - EG_LOG_KEY
      - DB_API_ENDPOINT
      - DB_API_ACCESS_KEY
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  cpz-connector:
    container_name: cpz-connector
    build:
      context: .
      dockerfile: CPZConnector.Dockerfile
    ports:
      - "8109:80"
    environment:
      - FUNCTIONS_WORKER_RUNTIME
      - AzureWebJobsStorage
      - API_KEY
      - PROXY_ENDPOINT
      - KEY_VAULT_URL
      - KEY_VAULT_READ_CLIENT_ID
      - KEY_VAULT_READ_APP_SECRET
      - KEY_VAULT_DECR_CLIENT_ID
      - KEY_VAULT_DECR_APP_SECRET
      - DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV
    restart: always
  nginx:
    container_name: nginx
    build: ./docker-nginx/
    ports:
      - "8100:443"
  # ngrok:
  #   container_name: ngrok
  #   ports:
  #     - "0.0.0.0:4040:4040"
  #   image: wernight/ngrok
  #   links:
  #     - "nginx"
  #   environment:
  #     - NGROK_PORT=nginx:80
