apiVersion: v1
kind: Service
metadata:
  labels:
    app: cpz-platform
  name: cpz-platform
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: cpz-platform
  type: ClusterIP
