module.exports = {
  ADVISER_SERVICE: "adviser",
  SUB_VALIDATION_EVENT: "Microsoft.EventGrid.SubscriptionValidationEvent",
  LOG_EVENT: "CPZ.Adviser.Log",
  ERROR_EVENT: "CPZ.Adviser.Error",
  TASKS_ADVISER_START_EVENT: "CPZ.Tasks.Adviser.Start",
  TASKS_ADVISER_STOP_EVENT: "CPZ.Tasks.Adviser.Stop",
  TASKS_ADVISER_UPDATE_EVENT: "CPZ.Tasks.Adviser.Update",
  TASKS_ADVISER_STARTED_EVENT: "CPZ.Tasks.Adviser.Started",
  TASKS_ADVISER_STOPPED_EVENT: "CPZ.Tasks.Adviser.Stopped",
  TASKS_CADVISER_UPDATED_EVENT: "CPZ.Tasks.Adviser.Updated",
  CANDLES_NEW_CANDLE_EVENT: "CPZ.Candles.NewCandle",
  CANDLES_HANDLED_EVENT: "CPZ.Candles.Handled",
  SIGNALS_NEW_SIGNAL_EVENT: "CPZ.Signals.NewSignal",
  STORAGE_ADVISERS_TABLE: "Advisers",
  STORAGE_CANDLESPENDING_TABLE: "CandlesPending",
  STATUS_STARTED: "started",
  STATUS_PENDING: "pending",
  STATUS_BUSY: "busy",
  STATUS_STOPPED: "stopped",
  STATUS_ERROR: "error",
  STATUS_FINISHED: "finished"
};
