const ADVISER_ERROR = "AdviserError";
const ADVISER_NOT_FOUND_ERROR = "AdviserNotFound";
const ADVISER_TASKS_EVENTS_ERROR = "AdviserTasksEventError";
const ADVISER_CANDLES_EVENTS_ERROR = "AdviserCandlesEventError";
const ADVISER_TIMER_ERROR = "AdviserTimerError";
const ADVISER_HANDLE_RUN_ERROR = "AdviserHandleRunError";
const ADVISER_HANDLE_CANDLE_ERROR = "AdviserHandleCandleError";
const ADVISER_START_ERROR = "AdviserStartError";
const ADVISER_STOP_ERROR = "AdviserStopError";
const ADVISER_UPDATE_ERROR = "AdviserUpdateError";
const ADVISER_PAUSE_ERROR = "AdviserPauseError";
const ADVISER_RESUME_ERROR = "AdviserResumeError";
const ADVISER_ACTION_TIMER_ERROR = "AdviserActionTimerError";
const ADVISER_LOAD_ACTIONS_ERROR = "AdviserLoadActionsError";
const ADVISER_EVENTS_PUBLISH_ERROR = "AdviserEventsPublishError";
const ADVISER_EVENT_PUBLISH_ERROR = "AdviserEventPublishError";
const ADVISER_EXECUTE_EXCEPTION = "AdviserExecuteException";
const ADVISER_EXECUTE_ERROR = "AdviserExecuteError";
const ADVISER_INDICATOR_ERROR = "AdviserIndicatorError";
const ADVISER_STRATEGY_ERROR = "AdviserStrategyError";
const ADVISER_SET_ERROR_ERROR = "AdviserSetErrorError";
const ADVISER_SAVE_STATE_ERROR = "AdviserSaveStateError";
const ADVISER_SAVE_STRATEGY_STATE_ERROR = "AdviserSaveStrategyStateError";
const ADVISER_SAVE_INDICATORS_STATE_ERROR = "AdviserSaveIndicatorsStateError";
const ADVISER_LOAD_CANDLES_ERROR = "AdviserLoadCandlesError";
const ADVISER_LOAD_STRATEGY_ERROR = "AdviserLoadStrategyError";
const ADVISER_LOAD_STRATEGY_STATE_ERROR = "AdviserLoadStrategyStateError";
const ADVISER_LOAD_INDICATOR_ERROR = "AdviserLoadIndicatorError";
const ADVISER_LOAD_INDICATORS_ERROR = "AdviserLoadIndicatorsError";
const ADVISER_LOAD_INDICATORS_STATE_ERROR = "AdviserLoadIndicatorsStateError";
const ADVISER_CREATE_LOCKFILE_ERROR = "AdviserCreateLockFileError";
const ADVISER_DEL_LOCKFILE_ERROR = "AdviserDelLockFileError";
const ADVISER_LOCK_ERROR = "AdviserLockError";
const ADVISER_UNLOCK_ERROR = "AdviserUnlockError";
const ADVISER_RENEW_LOCK_ERROR = "AdviserRenewLockError";
const ADVISER_GET_UNLOCKED_ERROR = "AdviserGetUnlockedError";
const ADVISER_CHECK_LOCKED_ERROR = "AdviserChecLockedError";
export {
  ADVISER_ERROR,
  ADVISER_NOT_FOUND_ERROR,
  ADVISER_TASKS_EVENTS_ERROR,
  ADVISER_CANDLES_EVENTS_ERROR,
  ADVISER_TIMER_ERROR,
  ADVISER_HANDLE_RUN_ERROR,
  ADVISER_HANDLE_CANDLE_ERROR,
  ADVISER_START_ERROR,
  ADVISER_STOP_ERROR,
  ADVISER_UPDATE_ERROR,
  ADVISER_PAUSE_ERROR,
  ADVISER_RESUME_ERROR,
  ADVISER_ACTION_TIMER_ERROR,
  ADVISER_LOAD_ACTIONS_ERROR,
  ADVISER_EVENTS_PUBLISH_ERROR,
  ADVISER_EVENT_PUBLISH_ERROR,
  ADVISER_EXECUTE_EXCEPTION,
  ADVISER_EXECUTE_ERROR,
  ADVISER_INDICATOR_ERROR,
  ADVISER_STRATEGY_ERROR,
  ADVISER_SET_ERROR_ERROR,
  ADVISER_SAVE_STATE_ERROR,
  ADVISER_SAVE_STRATEGY_STATE_ERROR,
  ADVISER_SAVE_INDICATORS_STATE_ERROR,
  ADVISER_LOAD_CANDLES_ERROR,
  ADVISER_LOAD_STRATEGY_ERROR,
  ADVISER_LOAD_STRATEGY_STATE_ERROR,
  ADVISER_LOAD_INDICATOR_ERROR,
  ADVISER_LOAD_INDICATORS_ERROR,
  ADVISER_LOAD_INDICATORS_STATE_ERROR,
  ADVISER_CREATE_LOCKFILE_ERROR,
  ADVISER_DEL_LOCKFILE_ERROR,
  ADVISER_LOCK_ERROR,
  ADVISER_UNLOCK_ERROR,
  ADVISER_RENEW_LOCK_ERROR,
  ADVISER_GET_UNLOCKED_ERROR,
  ADVISER_CHECK_LOCKED_ERROR
};
