const BACKTESTER_ALREADY_STARTED = "BacktesterAlreadyStarted";
const BACKTESTER_NOT_FOUND_ERROR = "BacktestNotFound";

const BACKTESTER_ERROR = "BacktesterError";
const BACKTEST_HISTORY_RANGE_ERROR = "BacktesterHistoryRangeError";
export {
  BACKTESTER_NOT_FOUND_ERROR,
  BACKTESTER_ALREADY_STARTED,
  BACKTESTER_ERROR,
  BACKTEST_HISTORY_RANGE_ERROR
};
