const BLOB_STORAGE_CONTAINER_CREATE_ERROR = "BlobStorageContainerCreateError";
const BLOB_STORAGE_BLOB_DELETE_ERROR = "BlobStorageBlobDeleteError";
const BLOB_STORAGE_BLOB_UPLOAD_ERROR = "BlobStorageBlobUploadError";
const BLOB_STORAGE_BLOB_DOWNLOAD_ERROR = "BlobStorageBlobDownloadError";
const BLOB_STORAGE_BLOB_GETPROPS_ERROR = "BlobStorageBlobGetPropsError";
const BLOB_STORAGE_BLOB_GETUNLOCKED_ERROR = "BlobStorageBlobGetUnlockedError";
const BLOB_STORAGE_BLOB_GETLEASEINFO_ERROR = "BlobStorageBlobGetLeaseInfoError";
const BLOB_STORAGE_BLOB_ACQUIRELEASE_ERROR = "BlobStorageBlobAcquireLeaseError";
const BLOB_STORAGE_BLOB_RENEWLEASE_ERROR = "BlobStorageBlobRenewLeaseError";
const BLOB_STORAGE_BLOB_RELEASELEASE_ERROR = "BlobStorageBlobReleaseLeaseError";

export {
  BLOB_STORAGE_CONTAINER_CREATE_ERROR,
  BLOB_STORAGE_BLOB_DELETE_ERROR,
  BLOB_STORAGE_BLOB_UPLOAD_ERROR,
  BLOB_STORAGE_BLOB_DOWNLOAD_ERROR,
  BLOB_STORAGE_BLOB_GETPROPS_ERROR,
  BLOB_STORAGE_BLOB_GETUNLOCKED_ERROR,
  BLOB_STORAGE_BLOB_GETLEASEINFO_ERROR,
  BLOB_STORAGE_BLOB_ACQUIRELEASE_ERROR,
  BLOB_STORAGE_BLOB_RENEWLEASE_ERROR,
  BLOB_STORAGE_BLOB_RELEASELEASE_ERROR
};
