const BLOB_STORAGE_CONTAINER_CREATE_ERROR = "BlobStorageContainerCreateError";
const BLOB_STORAGE_BLOB_UPLOAD_ERROR = "BlobStorageBlobUploadError";
const BLOB_STORAGE_BLOB_DOWNLOAD_ERROR = "BlobStorageBlobDownloadError";
export {
  BLOB_STORAGE_CONTAINER_CREATE_ERROR,
  BLOB_STORAGE_BLOB_UPLOAD_ERROR,
  BLOB_STORAGE_BLOB_DOWNLOAD_ERROR
};
