const CANDLEBATCHER_NOT_FOUND_ERROR = "CandlebatcherNotFound";
const CANDLEBATCHER_ERROR = "CandlebatcherError";
const CANDLEBATCHER_TASKS_EVENTS_ERROR = "CandlebatcherTasksEventError";
const CANDLEBATCHER_TIMER_ERROR = "CandlebatcherTimerError";
const CANDLEBATCHER_HANDLE_RUN_ERROR = "CandlebatcherHandleRunError";
const CANDLEBATCHER_START_ERROR = "CandlebatcherStartError";
const CANDLEBATCHER_STOP_ERROR = "CandlebatcherStopError";
const CANDLEBATCHER_UPDATE_ERROR = "CandlebatcherUpdateError";
const CANDLEBATCHER_ACTION_TIMER_ERROR = "CandlebatcherActionTimerError";
const CANDLEBATCHER_LOAD_ACTIONS_ERROR = "CandlebatcherLoadActionsError";
const CANDLEBATCHER_EVENTS_PUBLISH_ERROR = "CandlebatcherEventsPublishError";
const CANDLEBATCHER_EVENT_PUBLISH_ERROR = "CandlebatcherEventPublishError";
const CANDLEBATCHER_EXECUTE_EXCEPTION = "CandlebatcherExecuteException";
const CANDLEBATCHER_EXECUTE_ERROR = "CandlebatcherExecuteError";
const CANDLEBATCHER_LOAD_CANDLE_ERROR = "CandlebatcherLoadCandleError";
const CANDLEBATCHER_CREATE_CANDLE_ERROR = "CandlebatcherCreateCandleError";
const CANDLEBATCHER_SAVE_CANDLES_ERROR = "CandlebatcherSaveCandlesError";
const CANDLEBATCHER_SAVE_CANDLE_ERROR = "CandlebatcherSaveCandleError";
const CANDLEBATCHER_CLEAR_TICKS_ERROR = "CandlebatcherClearTicksError";
const CANDLEBATCHER_CLEAN_CACHED_CANDLES_ERROR =
  "CandlebatcherCleanCachedCandlesError";
const CANDLEBATCHER_SET_ERROR_ERROR = "CandlebatcherSetErrorError";
const CANDLEBATCHER_SAVE_STATE_ERROR = "CandlebatcherSaveStateError";
export {
  CANDLEBATCHER_NOT_FOUND_ERROR,
  CANDLEBATCHER_ERROR,
  CANDLEBATCHER_TASKS_EVENTS_ERROR,
  CANDLEBATCHER_TIMER_ERROR,
  CANDLEBATCHER_HANDLE_RUN_ERROR,
  CANDLEBATCHER_START_ERROR,
  CANDLEBATCHER_STOP_ERROR,
  CANDLEBATCHER_UPDATE_ERROR,
  CANDLEBATCHER_ACTION_TIMER_ERROR,
  CANDLEBATCHER_LOAD_ACTIONS_ERROR,
  CANDLEBATCHER_EVENTS_PUBLISH_ERROR,
  CANDLEBATCHER_EVENT_PUBLISH_ERROR,
  CANDLEBATCHER_EXECUTE_EXCEPTION,
  CANDLEBATCHER_EXECUTE_ERROR,
  CANDLEBATCHER_LOAD_CANDLE_ERROR,
  CANDLEBATCHER_CREATE_CANDLE_ERROR,
  CANDLEBATCHER_SAVE_CANDLES_ERROR,
  CANDLEBATCHER_SAVE_CANDLE_ERROR,
  CANDLEBATCHER_CLEAR_TICKS_ERROR,
  CANDLEBATCHER_CLEAN_CACHED_CANDLES_ERROR,
  CANDLEBATCHER_SET_ERROR_ERROR,
  CANDLEBATCHER_SAVE_STATE_ERROR
};
