const CONNECTOR_ERROR = "ConnectorError";
const CONNECTOR_CLIENT_ERROR = "ConnectorClientError";
const CONNECTOR_API_ERROR = "ConnectorAPIError";
const CONNECTOR_LOAD_API_KEYS_ERROR = "ConnectorLoadAPIKeysError";
const CONNECTOR_LOAD_DECR_SECR_ERROR = "ConnectorLoadAndDecryptSecretError";
const CONNECTOR_INIT_PR_PROVIDER_ERROR = "ConnectorInitPrivateProviderError";
const CONNECTOR_INIT_PUBLIC_PROVIDER_ERROR = "ConnectorInitPublicProviderError";
const CONNECTOR_EXCHANGE_ERROR = "ConnectorExchangeError";
const CONNECTOR_EMPTY_RESPONSE = "ConnectorEmptyResponse";
export {
  CONNECTOR_ERROR,
  CONNECTOR_CLIENT_ERROR,
  CONNECTOR_API_ERROR,
  CONNECTOR_LOAD_API_KEYS_ERROR,
  CONNECTOR_LOAD_DECR_SECR_ERROR,
  CONNECTOR_INIT_PR_PROVIDER_ERROR,
  CONNECTOR_INIT_PUBLIC_PROVIDER_ERROR,
  CONNECTOR_EXCHANGE_ERROR,
  CONNECTOR_EMPTY_RESPONSE
};
