const EVENTSLOGGER_HANDLE_EVENT_ERROR = "EventsLoggerHandleEventError";
const EVENTSLOGGER_LOG_EVENT_ERROR = "EventsLoggerLogEventError";
export { EVENTSLOGGER_HANDLE_EVENT_ERROR, EVENTSLOGGER_LOG_EVENT_ERROR };
