const IMPORTER_ERROR = "ImporterError";
const IMPORTER_TASKS_EVENTS_ERROR = "ImporterTasksEventError";
const IMPORTER_HANDLE_GAPS_ERROR = "ImporterHandleGapsError";
const IMPORTER_BATCH_CANDLES_ERROR = "ImporterBatchCandlesError";
const IMPORTER_SAVE_CANDLES_ERROR = "ImporterSaveCandlesError";
const IMPORTER_CLEAR_TEMP_ERROR = "ImporterClaerTempError";
const IMPORTER_SAVE_STATE_ERROR = "ImporterSaveStateError";
const IMPORTER_LOAD_CANDLES_ERROR = "ImporterLoadCandlesError";
export {
  IMPORTER_ERROR,
  IMPORTER_TASKS_EVENTS_ERROR,
  IMPORTER_HANDLE_GAPS_ERROR,
  IMPORTER_BATCH_CANDLES_ERROR,
  IMPORTER_SAVE_CANDLES_ERROR,
  IMPORTER_CLEAR_TEMP_ERROR,
  IMPORTER_SAVE_STATE_ERROR,
  IMPORTER_LOAD_CANDLES_ERROR
};
