const MARKETWATCHER_NOT_FOUND_ERROR = "MarketwatcherNotFound";
const MARKETWATCHER_ERROR = "MarketwatcherError";
const MARKETWATCHER_TASKS_EVENTS_ERROR = "MarketwatcherTasksEventsError";
const MARKETWATCHER_PUBLISH_TICK_ERROR = "MarketwatcherPublishTickError";
const MARKETWATCHER_SAVE_TICK_ERROR = "MarketwatcherSaveTickError";
const MARKETWATCHER_SOCKET_ERROR = "MarketwatcherSocketError";
export {
  MARKETWATCHER_NOT_FOUND_ERROR,
  MARKETWATCHER_ERROR,
  MARKETWATCHER_SOCKET_ERROR,
  MARKETWATCHER_TASKS_EVENTS_ERROR,
  MARKETWATCHER_PUBLISH_TICK_ERROR,
  MARKETWATCHER_SAVE_TICK_ERROR
};
