const MARKETWATCHER_NOT_FOUND_ERROR = "MarketwatcherNotFound";

const MARKETWATCHER_ERROR = "MarketwatcherError";

const CRYPTOCOMPARE_STREAMING_ERROR = "CryptocompareStreamingError";

export {
  MARKETWATCHER_NOT_FOUND_ERROR,
  MARKETWATCHER_ERROR,
  CRYPTOCOMPARE_STREAMING_ERROR
};
