const TRADER_ERROR = "TraderError";
const TRADER_EXECUTE_ERROR = "TraderExecuteError";
const TRADER_EXECUTE_ORDER_ERROR = "TradersExecuteOrderError";
const TRADER_EXECUTE_ORDERS_ERROR = "TradersExecuteOrdersError";
const TRADER_HANDLE_ORDERS_ERROR = "TraderHandleOrdersError";
const TRADER_HANDLE_SIGNAL_ERROR = "TraderHandleSignalError";
const TRADER_CHECK_PRICE_ERROR = "TraderCheckPriceError";
const TRADER_CHECK_ORDERS_ERROR = "TraderCheckOrdersError";
const TRADER_NOT_FOUND_ERROR = "TraderNotFound";
const TRADER_START_ERROR = "TradersStartError";
const TRADER_UPDATE_ERROR = "TradersUpdateError";
const TRADER_STOP_ERROR = "TradersStopError";
const TRADER_SET_ERROR_ERROR = "TradersSetErrorError";
const TRADER_TICKS_EVENTS_ERROR = "TraderTicksEventsError";
const TRADER_CANDLES_EVENTS_ERROR = "TraderCandlesEventsError";
const TRADER_PRICES_EVENTS_ERROR = "TraderPricesEventsError";
const TRADER_SIGNALS_EVENTS_ERROR = "TraderSignalsEventsError";
const TRADER_TASKS_EVENTS_ERROR = "TraderTasksEventsError";
const TRADER_TIMER_ERROR = "TraderTimerError";
const TRADER_CLOSE_ACTIVE_POSITIONS_ERROR = "TraderCloseActivePositionsError";
const TRADER_POSITION_NOT_FOUND_ERROR = "TraderPositionNotFound";
const TRADER_CREATE_POSITION_ERROR = "TraderCreatePositionError";
const TRADER_CLOSE_POSITION_ERROR = "TraderClosePositionError";
const TRADER_GET_CURRENT_PRICE_ERROR = "TraderGetCurrentPriceError";
const TRADER_SAVE_STATE_ERROR = "TraderSaveStateError";
const TRADER_EVENTS_PUBLISH_ERROR = "TraderEventsPublishError";
const TRADER_LOAD_ACTIONS_ERROR = "TraderLoadActionsError";
const TRADER_ORCHESTRATOR_ERROR = "TraderOrchestratorError";
const TRADER_ORCHESTRATOR_EXCEPTION = "TraderOrchestratorException";
export {
  TRADER_HANDLE_SIGNAL_ERROR,
  TRADER_HANDLE_ORDERS_ERROR,
  TRADER_NOT_FOUND_ERROR,
  TRADER_EXECUTE_ORDER_ERROR,
  TRADER_EXECUTE_ORDERS_ERROR,
  TRADER_CHECK_PRICE_ERROR,
  TRADER_CHECK_ORDERS_ERROR,
  TRADER_START_ERROR,
  TRADER_UPDATE_ERROR,
  TRADER_STOP_ERROR,
  TRADER_SET_ERROR_ERROR,
  TRADER_ERROR,
  TRADER_TICKS_EVENTS_ERROR,
  TRADER_CANDLES_EVENTS_ERROR,
  TRADER_SIGNALS_EVENTS_ERROR,
  TRADER_TASKS_EVENTS_ERROR,
  TRADER_TIMER_ERROR,
  TRADER_PRICES_EVENTS_ERROR,
  TRADER_CLOSE_ACTIVE_POSITIONS_ERROR,
  TRADER_POSITION_NOT_FOUND_ERROR,
  TRADER_CREATE_POSITION_ERROR,
  TRADER_CLOSE_POSITION_ERROR,
  TRADER_GET_CURRENT_PRICE_ERROR,
  TRADER_SAVE_STATE_ERROR,
  TRADER_EVENTS_PUBLISH_ERROR,
  TRADER_LOAD_ACTIONS_ERROR,
  TRADER_ORCHESTRATOR_ERROR,
  TRADER_ORCHESTRATOR_EXCEPTION,
  TRADER_EXECUTE_ERROR
};
