const TRADER_ERROR = "TraderError";
const TRADER_EXECUTE_ERROR = "TraderExecuteError";
const TRADER_EXECUTE_ORDER_ERROR = "TradersExecuteOrderError";
const TRADER_HANDLE_ORDERS_ERROR = "TraderHandleOrdersError";
const TRADER_HANDLE_SIGNAL_ERROR = "TraderHandleSignalError";
const TRADER_HANDLE_RUN_ERROR = "TraderHandleRunError";
const TRADER_CHECK_PRICE_ERROR = "TraderCheckPriceError";
const TRADER_NOT_FOUND_ERROR = "TraderNotFound";
const TRADER_START_ERROR = "TraderStartError";
const TRADER_UPDATE_ERROR = "TraderUpdateError";
const TRADER_STOP_ERROR = "TraderStopError";
const TRADER_PAUSE_ERROR = "TraderPauseError";
const TRADER_RESUME_ERROR = "TraderResumeError";
const TRADER_SET_ERROR_ERROR = "TradersSetErrorError";
const TRADER_TICKS_EVENTS_ERROR = "TraderTicksEventsError";
const TRADER_CANDLES_EVENTS_ERROR = "TraderCandlesEventsError";
const TRADER_PRICES_EVENTS_ERROR = "TraderPricesEventsError";
const TRADER_SIGNALS_EVENTS_ERROR = "TraderSignalsEventsError";
const TRADER_TASKS_EVENTS_ERROR = "TraderTasksEventsError";
const TRADER_IDLE_TIMER_ERROR = "TraderIdleTimerError";
const TRADER_ACTION_TIMER_ERROR = "TraderActionTimerError";
const TRADER_CLOSE_ACTIVE_POSITIONS_ERROR = "TraderCloseActivePositionsError";
const TRADER_CREATE_POSITION_ERROR = "TraderCreatePositionError";
const TRADER_CLOSE_POSITION_ERROR = "TraderClosePositionError";
const TRADER_SAVE_STATE_ERROR = "TraderSaveStateError";
const TRADER_EVENTS_PUBLISH_ERROR = "TraderEventsPublishError";
const TRADER_EVENT_PUBLISH_ERROR = "TraderEventPublishError";
const TRADER_LOAD_ACTIONS_ERROR = "TraderLoadActionsError";
const TRADER_EXECUTE_EXCEPTION = "TraderExecuteException";
const TRADER_CREATE_LOCKFILE_ERROR = "TraderCreateLockFileError";
const TRADER_DEL_LOCKFILE_ERROR = "TraderDelLockFileError";
const TRADER_LOCK_ERROR = "TraderLockError";
const TRADER_UNLOCK_ERROR = "TraderUnlockError";
const TRADER_RENEW_LOCK_ERROR = "TraderRenewLockError";
const TRADER_GET_UNLOCKED_ERROR = "TraderGetUnlockedError";
const TRADER_CHECK_LOCKED_ERROR = "TraderChecLockedError";
const TRADER_LOAD_CURRENT_PRICE_ERROR = "TraderLoadCurrentPriceError";
const TRADER_HANDLE_CURRENT_PRICE_ERROR = "TraderHandleCurrentPriceError";
export {
  TRADER_HANDLE_SIGNAL_ERROR,
  TRADER_HANDLE_ORDERS_ERROR,
  TRADER_NOT_FOUND_ERROR,
  TRADER_EXECUTE_ORDER_ERROR,
  TRADER_CHECK_PRICE_ERROR,
  TRADER_START_ERROR,
  TRADER_UPDATE_ERROR,
  TRADER_PAUSE_ERROR,
  TRADER_RESUME_ERROR,
  TRADER_STOP_ERROR,
  TRADER_SET_ERROR_ERROR,
  TRADER_ERROR,
  TRADER_TICKS_EVENTS_ERROR,
  TRADER_CANDLES_EVENTS_ERROR,
  TRADER_SIGNALS_EVENTS_ERROR,
  TRADER_TASKS_EVENTS_ERROR,
  TRADER_IDLE_TIMER_ERROR,
  TRADER_ACTION_TIMER_ERROR,
  TRADER_PRICES_EVENTS_ERROR,
  TRADER_CLOSE_ACTIVE_POSITIONS_ERROR,
  TRADER_CREATE_POSITION_ERROR,
  TRADER_CLOSE_POSITION_ERROR,
  TRADER_SAVE_STATE_ERROR,
  TRADER_EVENTS_PUBLISH_ERROR,
  TRADER_EVENT_PUBLISH_ERROR,
  TRADER_LOAD_ACTIONS_ERROR,
  TRADER_EXECUTE_EXCEPTION,
  TRADER_EXECUTE_ERROR,
  TRADER_HANDLE_RUN_ERROR,
  TRADER_CREATE_LOCKFILE_ERROR,
  TRADER_DEL_LOCKFILE_ERROR,
  TRADER_LOCK_ERROR,
  TRADER_UNLOCK_ERROR,
  TRADER_RENEW_LOCK_ERROR,
  TRADER_GET_UNLOCKED_ERROR,
  TRADER_CHECK_LOCKED_ERROR,
  TRADER_LOAD_CURRENT_PRICE_ERROR,
  TRADER_HANDLE_CURRENT_PRICE_ERROR
};
