const CLOSE_ACTIVE_POSITION_ERROR = "CloseActivePositions";

const POSITION_NOT_FOUND_ERROR = "PositionNotFound";

const CREATE_POSITION_ERROR = "CreatePositionError";

const CLOSE_POSITION_ERROR = "ClosePosition";

export {
  CLOSE_ACTIVE_POSITION_ERROR,
  POSITION_NOT_FOUND_ERROR,
  CREATE_POSITION_ERROR,
  CLOSE_POSITION_ERROR
};
