import { IMPORTER_SERVICE } from "cpz/config/services";
import {
  BASE_EVENT,
  SUB_DELETED_EVENT,
  SUB_VALIDATION_EVENT
} from "cpz/events/types/base";

import schemas from "cpz/events/schemas";
import {
  ERROR_IMPORTER_EVENT,
  LOG_IMPORTER_EVENT,
  TASKS_IMPORTER_FINISHED_EVENT,
  TASKS_IMPORTER_START_EVENT,
  TASKS_IMPORTER_STARTED_EVENT,
  TASKS_IMPORTER_STOP_EVENT,
  TASKS_IMPORTER_STOPPED_EVENT
} from "cpz/config/events/types";
import { ERROR_TOPIC, LOG_TOPIC, TASKS_TOPIC } from "cpz/events/topics";

export default {
  serviceName: IMPORTER_SERVICE,
  events: {
    topics: { ERROR_TOPIC, LOG_TOPIC, TASKS_TOPIC },
    types: {
      BASE_EVENT,
      SUB_VALIDATION_EVENT,
      SUB_DELETED_EVENT,
      TASKS_IMPORTER_START_EVENT,
      TASKS_IMPORTER_STOP_EVENT,
      TASKS_IMPORTER_STARTED_EVENT,
      TASKS_IMPORTER_STOPPED_EVENT,
      TASKS_IMPORTER_FINISHED_EVENT,
      LOG_IMPORTER_EVENT,
      ERROR_IMPORTER_EVENT
    },
    schemas: {
      [BASE_EVENT]: schemas[BASE_EVENT],
      [TASKS_IMPORTER_START_EVENT]: schemas[TASKS_IMPORTER_START_EVENT],
      [TASKS_IMPORTER_STOP_EVENT]: schemas[TASKS_IMPORTER_STOP_EVENT],
      [TASKS_IMPORTER_STARTED_EVENT]: schemas[TASKS_IMPORTER_STARTED_EVENT],
      [TASKS_IMPORTER_STOPPED_EVENT]: schemas[TASKS_IMPORTER_STOPPED_EVENT],
      [TASKS_IMPORTER_FINISHED_EVENT]: schemas[TASKS_IMPORTER_FINISHED_EVENT],
      [LOG_IMPORTER_EVENT]: schemas[LOG_IMPORTER_EVENT],
      [ERROR_IMPORTER_EVENT]: schemas[ERROR_IMPORTER_EVENT],
      [LOG_IMPORTER_EVENT]: schemas[LOG_IMPORTER_EVENT],
      [ERROR_IMPORTER_EVENT]: schemas[ERROR_IMPORTER_EVENT]
    }
  }
};
