export default [
  "FUNCTIONS_WORKER_RUNTIME",
  "AzureWebJobsStorage",
  "AZ_STORAGE_TRADE_CS",
  "AZ_STORAGE_MARKET_CS",
  "API_KEY",
  "EG_TASKS_ENDPOINT",
  "EG_TASKS_KEY",
  "EG_LOG_ENDPOINT",
  "EG_LOG_KEY",
  "EG_SIGNALS_ENDPOINT",
  "EG_SIGNALS_KEY",
  "EG_CANDLES_ENDPOINT",
  "EG_CANDLES_KEY",
  "DEBUG"
];
