export default [
  "FUNCTIONS_WORKER_RUNTIME",
  "AzureWebJobsStorage",
  "API_KEY",
  "DB_API_ENDPOINT",
  "DB_API_ACCESS_KEY",
  "CONNECTOR_API_ENDPOINT",
  "CONNECTOR_API_KEY",
  "KEY_VAULT_URL",
  "KEY_VAULT_WRITE_CLIENT_ID",
  "KEY_VAULT_WRITE_APP_SECRET"
];
