export default [
  "AzureWebJobsStorage",
  "AZ_STORAGE_BACKTESTER_CS",
  "AZ_STORAGE_BLOB_NAME",
  "AZ_STORAGE_BLOB_KEY",
  "API_KEY",
  "EG_TASKS_ENDPOINT",
  "EG_TASKS_KEY",
  "EG_LOG_ENDPOINT",
  "EG_LOG_KEY",
  "EG_ERROR_ENDPOINT",
  "EG_ERROR_KEY",
  "DB_API_ENDPOINT",
  "DB_API_ACCESS_KEY",
  "DEBUG"
];
