export default [
  "FUNCTIONS_WORKER_RUNTIME",
  "AzureWebJobsStorage",
  "API_KEY",
  "PROXY_ENDPOINT_PUBLIC",
  "PROXY_ENDPOINT_PRIVATE",
  "KEY_VAULT_URL",
  "KEY_VAULT_READ_CLIENT_ID",
  "KEY_VAULT_READ_APP_SECRET",
  "KEY_VAULT_DECR_CLIENT_ID",
  "KEY_VAULT_DECR_APP_SECRET"
];
