export default [
  "FUNCTIONS_WORKER_RUNTIME",
  "AzureWebJobsStorage",
  "AZ_STORAGE_EVENT_CS",
  "AZ_STORAGE_MARKET_CS",
  "EG_EMULATOR_MODE",
  "LOG_TABLE_STORAGE",
  "LOG_POSTGRE",
  "DB_API_ENDPOINT",
  "DB_API_ACCESS_KEY",
  "API_KEY"
];
