export default [
  "AzureWebJobsStorage",
  "AZ_STORAGE_CONTROL_CS",
  "AZ_STORAGE_MARKET_CS",
  "API_KEY",
  "EG_TASKS_ENDPOINT",
  "EG_TASKS_KEY",
  "EG_LOG_ENDPOINT",
  "EG_LOG_KEY",
  "EG_ERROR_ENDPOINT",
  "EG_ERROR_KEY",
  "DB_API_ENDPOINT",
  "DB_API_ACCESS_KEY",
  "CONNECTOR_API_ENDPOINT",
  "CONNECTOR_API_KEY",
  "DEBUG"
];
