const TASKS_ADVISER_START_EVENT = "CPZ.Tasks.Adviser.Start";
const TASKS_ADVISER_STOP_EVENT = "CPZ.Tasks.Adviser.Stop";
const TASKS_ADVISER_UPDATE_EVENT = "CPZ.Tasks.Adviser.Update";
const TASKS_ADVISER_STARTED_EVENT = "CPZ.Tasks.Adviser.Started";
const TASKS_ADVISER_STOPPED_EVENT = "CPZ.Tasks.Adviser.Stopped";
const TASKS_ADVISER_UPDATED_EVENT = "CPZ.Tasks.Adviser.Updated";
const TASKS_ADVISER_RUN_EVENT = "CPZ.Tasks.Adviser.Run";
export {
  TASKS_ADVISER_START_EVENT,
  TASKS_ADVISER_STARTED_EVENT,
  TASKS_ADVISER_STOP_EVENT,
  TASKS_ADVISER_STOPPED_EVENT,
  TASKS_ADVISER_UPDATE_EVENT,
  TASKS_ADVISER_UPDATED_EVENT,
  TASKS_ADVISER_RUN_EVENT
};
