const TASKS_BACKTESTER_START_EVENT = "CPZ.Tasks.Backtester.Start";
const TASKS_BACKTESTER_STOP_EVENT = "CPZ.Tasks.Backtester.Stop";
const TASKS_BACKTESTER_STARTED_EVENT = "CPZ.Tasks.Backtester.Started";
const TASKS_BACKTESTER_STOPPED_EVENT = "CPZ.Tasks.Backtester.Stopped";
const TASKS_BACKTESTER_FINISHED_EVENT = "CPZ.Tasks.Backtester.Finished";
export {
  TASKS_BACKTESTER_START_EVENT,
  TASKS_BACKTESTER_STOP_EVENT,
  TASKS_BACKTESTER_STARTED_EVENT,
  TASKS_BACKTESTER_STOPPED_EVENT,
  TASKS_BACKTESTER_FINISHED_EVENT
};
