const BACKTEST_START = "Backtest.Start";
const BACKTEST_STOP = "Backtest.Stop";
const TASKS_BACKTEST_STARTED_EVENT = "CPZ.Tasks.Backtest.Started";
const TASKS_BACKTEST_STOPPED_EVENT = "CPZ.Tasks.Backtest.Stopped";
const TASKS_BACKTEST_FINISHED_EVENT = "CPZ.Tasks.Backtest.Finished";
export {
  BACKTEST_START,
  BACKTEST_STOP,
  TASKS_BACKTEST_STARTED_EVENT,
  TASKS_BACKTEST_STOPPED_EVENT,
  TASKS_BACKTEST_FINISHED_EVENT
};
