const TASKS_CANDLEBATCHER_START_EVENT = "CPZ.Tasks.Candlebatcher.Start";
const TASKS_CANDLEBATCHER_STOP_EVENT = "CPZ.Tasks.Candlebatcher.Stop";
const TASKS_CANDLEBATCHER_UPDATE_EVENT = "CPZ.Tasks.Candlebatcher.Update";
const TASKS_CANDLEBATCHER_STARTED_EVENT = "CPZ.Tasks.Candlebatcher.Started";
const TASKS_CANDLEBATCHER_STOPPED_EVENT = "CPZ.Tasks.Candlebatcher.Stopped";
const TASKS_CANDLEBATCHER_UPDATED_EVENT = "CPZ.Tasks.Candlebatcher.Updated";
const TASKS_CANDLEBATCHER_RUN_EVENT = "CPZ.Tasks.Candlebatcher.Run";
const TASKS_CANDLEBATCHER_PAUSE_EVENT = "CPZ.Tasks.Candlebatcher.Pause";
const TASKS_CANDLEBATCHER_RESUME_EVENT = "CPZ.Tasks.Candlebatcher.Resume";
export {
  TASKS_CANDLEBATCHER_START_EVENT,
  TASKS_CANDLEBATCHER_STARTED_EVENT,
  TASKS_CANDLEBATCHER_STOP_EVENT,
  TASKS_CANDLEBATCHER_STOPPED_EVENT,
  TASKS_CANDLEBATCHER_UPDATE_EVENT,
  TASKS_CANDLEBATCHER_UPDATED_EVENT,
  TASKS_CANDLEBATCHER_RUN_EVENT,
  TASKS_CANDLEBATCHER_PAUSE_EVENT,
  TASKS_CANDLEBATCHER_RESUME_EVENT
};
