const EXWATCHER_START = "Exwatcher.Start";
const TASKS_EXWATCHER_STARTED_EVENT = "CPZ.Tasks.Exwatcher.Started";
const TASKS_EXWATCHER_STOPPED_EVENT = "CPZ.Tasks.Exwatcher.Stopped";
export {
  EXWATCHER_START,
  TASKS_EXWATCHER_STARTED_EVENT,
  TASKS_EXWATCHER_STOPPED_EVENT
};
