const EXWATCHER_START = "Exwatcher.Start";
const EXWATCHER_STOP = "Exwatcher.Stop";
const EXWATCHER_UPDATE = "Exwatcher.Update";
const TASKS_EXWATCHER_STARTED_EVENT = "CPZ.Tasks.Exwatcher.Started";
const TASKS_EXWATCHER_STOPPED_EVENT = "CPZ.Tasks.Exwatcher.Stopped";
const TASKS_EXWATCHER_UPDATED_EVENT = "CPZ.Tasks.Exwatcher.Updated";
export {
  EXWATCHER_START,
  EXWATCHER_STOP,
  EXWATCHER_UPDATE,
  TASKS_EXWATCHER_STARTED_EVENT,
  TASKS_EXWATCHER_STOPPED_EVENT,
  TASKS_EXWATCHER_UPDATED_EVENT
};
