const TASKS_MARKETWATCHER_START_EVENT = "CPZ.Tasks.Marketwatcher.Start";
const TASKS_MARKETWATCHER_STOP_EVENT = "CPZ.Tasks.Marketwatcher.Stop";
const TASKS_MARKETWATCHER_SUBSCRIBE_EVENT = "CPZ.Tasks.Marketwatcher.Subscribe";
const TASKS_MARKETWATCHER_UNSUBSCRIBE_EVENT =
  "CPZ.Tasks.Marketwatcher.Unsubscribe";
const TASKS_MARKETWATCHER_STARTED_EVENT = "CPZ.Tasks.Marketwatcher.Started";
const TASKS_MARKETWATCHER_STOPPED_EVENT = "CPZ.Tasks.Marketwatcher.Stopped";
const TASKS_MARKETWATCHER_UPDATED_EVENT = "CPZ.Tasks.Marketwatcher.Updated";
export {
  TASKS_MARKETWATCHER_START_EVENT,
  TASKS_MARKETWATCHER_STARTED_EVENT,
  TASKS_MARKETWATCHER_STOP_EVENT,
  TASKS_MARKETWATCHER_STOPPED_EVENT,
  TASKS_MARKETWATCHER_SUBSCRIBE_EVENT,
  TASKS_MARKETWATCHER_UNSUBSCRIBE_EVENT,
  TASKS_MARKETWATCHER_UPDATED_EVENT
};
