const TASKS_TRADER_START_EVENT = "CPZ.Tasks.Trader.Start";
const TASKS_TRADER_STOP_EVENT = "CPZ.Tasks.Trader.Stop";
const TASKS_TRADER_UPDATE_EVENT = "CPZ.Tasks.Trader.Update";
const TASKS_TRADER_STARTED_EVENT = "CPZ.Tasks.Trader.Started";
const TASKS_TRADER_STOPPED_EVENT = "CPZ.Tasks.Trader.Stopped";
const TASKS_TRADER_UPDATED_EVENT = "CPZ.Tasks.Trader.Updated";
const TASKS_TRADER_RUN_EVENT = "CPZ.Tasks.Trader.Run";
export {
  TASKS_TRADER_START_EVENT,
  TASKS_TRADER_STARTED_EVENT,
  TASKS_TRADER_STOP_EVENT,
  TASKS_TRADER_STOPPED_EVENT,
  TASKS_TRADER_UPDATE_EVENT,
  TASKS_TRADER_UPDATED_EVENT,
  TASKS_TRADER_RUN_EVENT
};
