const USER_ROBOT_START = "UserRobot.Start";
const USER_ROBOT_STOP = "UserRobot.Stop";
const USER_ROBOT_UPDATE = "UserRobot.Update";
const TASKS_USERROBOT_STARTED_EVENT = "CPZ.Tasks.UserRobot.Started";
const TASKS_USERROBOT_STOPPED_EVENT = "CPZ.Tasks.UserRobot.Stopped";
const TASKS_USERROBOT_UPDATED_EVENT = "CPZ.Tasks.UserRobot.Updated";
export {
  USER_ROBOT_START,
  USER_ROBOT_STOP,
  USER_ROBOT_UPDATE,
  TASKS_USERROBOT_STARTED_EVENT,
  TASKS_USERROBOT_STOPPED_EVENT,
  TASKS_USERROBOT_UPDATED_EVENT
};
