import {
  ADVISER_SERVICE, BACKTESTER_SERVICE,
  CANDLEBATCHER_SERVICE,
  CONTROL_SERVICE, EXWATCHER_SERVICE, IMPORTER_SERVICE,
  MARKETWATCHER_SERVICE, TRADER_SERVICE
} from "cpz/config/services";
import {
  BASE_EVENT,
  SUB_DELETED_EVENT,
  SUB_VALIDATION_EVENT
} from "cpz/events/types/base";
import schemas from "cpz/events/schemas";
import {
  BACKTEST_START_PARAMS,
  BACKTEST_STOP_PARAMS,
  ERROR_CONTROL_EVENT,
  EXWATCHER_START_PARAMS,
  EXWATCHER_STOP_PARAMS,
  EXWATCHER_UPDATE_PARAMS,
  TASKS_ADVISER_START_EVENT,
  TASKS_ADVISER_STOP_EVENT,
  TASKS_ADVISER_UPDATE_EVENT,
  TASKS_BACKTEST_FINISHED_EVENT,
  TASKS_BACKTEST_STARTED_EVENT,
  TASKS_BACKTEST_STOPPED_EVENT,
  TASKS_BACKTESTER_START_EVENT,
  TASKS_BACKTESTER_STOP_EVENT,
  TASKS_CANDLEBATCHER_START_EVENT,
  TASKS_CANDLEBATCHER_STOP_EVENT,
  TASKS_CANDLEBATCHER_UPDATE_EVENT,
  TASKS_EXWATCHER_STARTED_EVENT,
  TASKS_EXWATCHER_STOPPED_EVENT,
  TASKS_IMPORTER_START_EVENT,
  TASKS_IMPORTER_STOP_EVENT,
  TASKS_MARKETWATCHER_START_EVENT,
  TASKS_MARKETWATCHER_STOP_EVENT,
  TASKS_MARKETWATCHER_SUBSCRIBE_EVENT,
  TASKS_MARKETWATCHER_UNSUBSCRIBE_EVENT,
  TASKS_TRADER_START_EVENT,
  TASKS_TRADER_STOP_EVENT,
  TASKS_TRADER_UPDATE_EVENT,
  TASKS_USERROBOT_STARTED_EVENT,
  TASKS_USERROBOT_STOPPED_EVENT,
  USER_ROBOT_START_PARAMS,
  USER_ROBOT_STOP_PARAMS,
  USER_ROBOT_UPDATE_PARAMS
} from "cpz/config/events/types";
import { TASKS_TOPIC, ERROR_TOPIC } from "cpz/events/topics";

export default {
  serviceName: CONTROL_SERVICE,
  services: {
    ADVISER_SERVICE,
    CONTROL_SERVICE,
    MARKETWATCHER_SERVICE,
    CANDLEBATCHER_SERVICE,
    TRADER_SERVICE,
    EXWATCHER_SERVICE,
    IMPORTER_SERVICE,
    BACKTESTER_SERVICE
  },
  events: {
    topics: { TASKS_TOPIC },
    types: {
      BASE_EVENT,
      SUB_VALIDATION_EVENT,
      SUB_DELETED_EVENT,
      TASKS_ADVISER_START_EVENT,
      TASKS_ADVISER_STOP_EVENT,
      TASKS_ADVISER_UPDATE_EVENT,
      TASKS_BACKTESTER_START_EVENT,
      TASKS_BACKTESTER_STOP_EVENT,
      TASKS_BACKTEST_STARTED_EVENT,
      TASKS_BACKTEST_STOPPED_EVENT,
      TASKS_BACKTEST_FINISHED_EVENT,
      BACKTEST_START_PARAMS,
      BACKTEST_STOP_PARAMS,
      TASKS_CANDLEBATCHER_START_EVENT,
      TASKS_CANDLEBATCHER_STOP_EVENT,
      TASKS_CANDLEBATCHER_UPDATE_EVENT,
      TASKS_IMPORTER_START_EVENT,
      TASKS_IMPORTER_STOP_EVENT,
      TASKS_MARKETWATCHER_START_EVENT,
      TASKS_MARKETWATCHER_STOP_EVENT,
      TASKS_MARKETWATCHER_SUBSCRIBE_EVENT,
      TASKS_MARKETWATCHER_UNSUBSCRIBE_EVENT,
      TASKS_TRADER_START_EVENT,
      TASKS_TRADER_STOP_EVENT,
      TASKS_TRADER_UPDATE_EVENT,
      TASKS_EXWATCHER_STARTED_EVENT,
      TASKS_EXWATCHER_STOPPED_EVENT,
      EXWATCHER_START_PARAMS,
      EXWATCHER_STOP_PARAMS,
      EXWATCHER_UPDATE_PARAMS,
      TASKS_USERROBOT_STARTED_EVENT,
      TASKS_USERROBOT_STOPPED_EVENT,
      USER_ROBOT_START_PARAMS,
      USER_ROBOT_STOP_PARAMS,
      USER_ROBOT_UPDATE_PARAMS,
      ERROR_CONTROL_EVENT,
      ERROR_TOPIC
    },
    schemas: {
      [BASE_EVENT]: schemas[BASE_EVENT],
      [TASKS_ADVISER_START_EVENT]: schemas[TASKS_ADVISER_START_EVENT],
      [TASKS_ADVISER_STOP_EVENT]: schemas[TASKS_ADVISER_STOP_EVENT],
      [TASKS_ADVISER_UPDATE_EVENT]: schemas[TASKS_ADVISER_UPDATE_EVENT],
      [TASKS_BACKTESTER_START_EVENT]: schemas[TASKS_BACKTESTER_START_EVENT],
      [TASKS_BACKTESTER_STOP_EVENT]: schemas[TASKS_BACKTESTER_STOP_EVENT],
      [BACKTEST_START_PARAMS]: schemas[BACKTEST_START_PARAMS],
      [BACKTEST_STOP_PARAMS]: schemas[BACKTEST_STOP_PARAMS],
      [TASKS_CANDLEBATCHER_START_EVENT]:
        schemas[TASKS_CANDLEBATCHER_START_EVENT],
      [TASKS_CANDLEBATCHER_STOP_EVENT]: schemas[TASKS_CANDLEBATCHER_STOP_EVENT],
      [TASKS_CANDLEBATCHER_UPDATE_EVENT]:
        schemas[TASKS_CANDLEBATCHER_UPDATE_EVENT],
      [TASKS_IMPORTER_START_EVENT]: schemas[TASKS_IMPORTER_START_EVENT],
      [TASKS_IMPORTER_STOP_EVENT]: schemas[TASKS_IMPORTER_STOP_EVENT],
      [TASKS_MARKETWATCHER_START_EVENT]:
        schemas[TASKS_MARKETWATCHER_START_EVENT],
      [TASKS_MARKETWATCHER_STOP_EVENT]: schemas[TASKS_MARKETWATCHER_STOP_EVENT],
      [TASKS_MARKETWATCHER_SUBSCRIBE_EVENT]:
        schemas[TASKS_MARKETWATCHER_SUBSCRIBE_EVENT],
      [TASKS_MARKETWATCHER_UNSUBSCRIBE_EVENT]:
        schemas[TASKS_MARKETWATCHER_UNSUBSCRIBE_EVENT],
      [TASKS_TRADER_START_EVENT]: schemas[TASKS_TRADER_START_EVENT],
      [TASKS_TRADER_STOP_EVENT]: schemas[TASKS_TRADER_STOP_EVENT],
      [TASKS_TRADER_UPDATE_EVENT]: schemas[TASKS_TRADER_UPDATE_EVENT],
      [EXWATCHER_START_PARAMS]: schemas[EXWATCHER_START_PARAMS],
      [EXWATCHER_STOP_PARAMS]: schemas[EXWATCHER_STOP_PARAMS],
      [EXWATCHER_UPDATE_PARAMS]: schemas[EXWATCHER_UPDATE_PARAMS],
      [USER_ROBOT_START_PARAMS]: schemas[USER_ROBOT_START_PARAMS],
      [USER_ROBOT_STOP_PARAMS]: schemas[USER_ROBOT_STOP_PARAMS],
      [USER_ROBOT_UPDATE_PARAMS]: schemas[USER_ROBOT_UPDATE_PARAMS]
    }
  }
};
