const STORAGE_ADVISERS_TABLE = "Advisers";
const STORAGE_BACKTESTS_TABLE = "Backtests";
const STORAGE_BACKTESTITEMS_TABLE = "BacktestItems";

const STORAGE_CANDLESCACHED_TABLE = "CandlesCached";
const STORAGE_CANDLESPENDING_TABLE = "CandlesPending";

export {
  STORAGE_ADVISERS_TABLE,
  STORAGE_BACKTESTS_TABLE,
  STORAGE_BACKTESTITEMS_TABLE,
  STORAGE_CANDLESCACHED_TABLE,
  STORAGE_CANDLESPENDING_TABLE
};
