const STORAGE_ADVISERS_TABLE = "Advisers";
const STORAGE_CANDLESCACHED_TABLE = "CandlesCached";
const STORAGE_CANDLESPENDING_TABLE = "CandlesPending";

export {
  STORAGE_ADVISERS_TABLE,
  STORAGE_CANDLESCACHED_TABLE,
  STORAGE_CANDLESPENDING_TABLE
};
