import { CANDLEBATCHER_SERVICE } from "cpz/config/services";
import {
  BASE_EVENT,
  SUB_VALIDATION_EVENT,
  SUB_DELETED_EVENT
} from "cpz/events/types/base";
import schemas from "cpz/events/schemas";
import {
  TASKS_CANDLEBATCHER_UPDATE_EVENT,
  TASKS_CANDLEBATCHER_STOP_EVENT,
  TASKS_CANDLEBATCHER_START_EVENT,
  TASKS_CANDLEBATCHER_STARTED_EVENT,
  TASKS_CANDLEBATCHER_STOPPED_EVENT,
  TASKS_CANDLEBATCHER_UPDATED_EVENT,
  ERROR_CANDLEBATCHER_EVENT,
  LOG_CANDLEBATCHER_EVENT
} from "cpz/config/events/types";

export default {
  serviceName: CANDLEBATCHER_SERVICE,
  events: {
    topics: {},
    types: {
      BASE_EVENT,
      SUB_VALIDATION_EVENT,
      SUB_DELETED_EVENT,
      TASKS_CANDLEBATCHER_START_EVENT,
      TASKS_CANDLEBATCHER_STOP_EVENT,
      TASKS_CANDLEBATCHER_UPDATE_EVENT,
      TASKS_CANDLEBATCHER_STARTED_EVENT,
      TASKS_CANDLEBATCHER_STOPPED_EVENT,
      TASKS_CANDLEBATCHER_UPDATED_EVENT,
      ERROR_CANDLEBATCHER_EVENT,
      LOG_CANDLEBATCHER_EVENT
    },
    schemas: {
      [BASE_EVENT]: schemas[BASE_EVENT],
      [SUB_DELETED_EVENT]: schemas[SUB_DELETED_EVENT],
      [TASKS_CANDLEBATCHER_START_EVENT]:
        schemas[TASKS_CANDLEBATCHER_START_EVENT],
      [TASKS_CANDLEBATCHER_STOP_EVENT]: schemas[TASKS_CANDLEBATCHER_STOP_EVENT],
      [TASKS_CANDLEBATCHER_UPDATE_EVENT]:
        schemas[TASKS_CANDLEBATCHER_UPDATE_EVENT],
      [ERROR_CANDLEBATCHER_EVENT]: schemas[ERROR_CANDLEBATCHER_EVENT],
      [LOG_CANDLEBATCHER_EVENT]: schemas[LOG_CANDLEBATCHER_EVENT],
      [TASKS_CANDLEBATCHER_STARTED_EVENT]:
        schemas[TASKS_CANDLEBATCHER_STARTED_EVENT],
      [TASKS_CANDLEBATCHER_STOPPED_EVENT]:
        schemas[TASKS_CANDLEBATCHER_STOPPED_EVENT],
      [TASKS_CANDLEBATCHER_UPDATED_EVENT]:
        schemas[TASKS_CANDLEBATCHER_UPDATED_EVENT]
    }
  }
};
