const STATUS_STARTED = "started";
const STATUS_PENDING = "pending";
const STATUS_BUSY = "busy";
const STATUS_STOPPED = "stopped";
const STATUS_ERROR = "error";
const STATUS_FINISHED = "finished";

const POS_STATUS_NONE = "none";
const POS_STATUS_ACTIVE = "active";
const POS_STATUS_POSTED = "posted";
const POS_STATUS_CANCELED = "canceled";
const POS_STATUS_ERROR = "error";
const POS_STATUS_PENDING = "pending";

const ORDER_STATUS_PENDING = "pending";
const ORDER_STATUS_OPEN = "open";
const ORDER_STATUS_CLOSED = "closed";
const ORDER_STATUS_POSTED = "posted";
const ORDER_STATUS_CANCELED = "canceled";
const ORDER_STATUS_ERROR = "error";

const ORDER_TASK_OPENBYMARKET = "openByMarket";
const ORDER_TASK_SETLIMIT = "setLimit";
const ORDER_TASK_CHECKLIMIT = "checkLimit";

export {
  STATUS_BUSY,
  STATUS_ERROR,
  STATUS_FINISHED,
  STATUS_PENDING,
  STATUS_STARTED,
  STATUS_STOPPED,
  POS_STATUS_NONE,
  POS_STATUS_ACTIVE,
  POS_STATUS_POSTED,
  POS_STATUS_CANCELED,
  POS_STATUS_ERROR,
  POS_STATUS_PENDING,
  ORDER_STATUS_PENDING,
  ORDER_STATUS_OPEN,
  ORDER_STATUS_CLOSED,
  ORDER_STATUS_POSTED,
  ORDER_STATUS_CANCELED,
  ORDER_STATUS_ERROR,
  ORDER_TASK_OPENBYMARKET,
  ORDER_TASK_SETLIMIT,
  ORDER_TASK_CHECKLIMIT
};
