const REALTIME_MODE = "realtime";
const EMULATOR_MODE = "emulator";
const BACKTEST_MODE = "backtest";

const TRADE_ACTION_LONG = "long";
const TRADE_ACTION_CLOSE_LONG = "closeLong";
const TRADE_ACTION_SHORT = "short";
const TRADE_ACTION_CLOSE_SHORT = "closeShort";

const ORDER_TYPE_LIMIT = "limit";
const ORDER_TYPE_MARKET = "market";
const ORDER_TYPE_STOP = "stop";

const ORDER_DIRECTION_BUY = "buy";
const ORDER_DIRECTION_SELL = "sell";

const ORDER_POS_DIR_OPEN = "open";
const ORDER_POS_DIR_CLOSE = "close";
export {
  REALTIME_MODE,
  EMULATOR_MODE,
  BACKTEST_MODE,
  TRADE_ACTION_LONG,
  TRADE_ACTION_CLOSE_LONG,
  TRADE_ACTION_SHORT,
  TRADE_ACTION_CLOSE_SHORT,
  ORDER_TYPE_LIMIT,
  ORDER_TYPE_MARKET,
  ORDER_TYPE_STOP,
  ORDER_DIRECTION_BUY,
  ORDER_DIRECTION_SELL,
  ORDER_POS_DIR_OPEN,
  ORDER_POS_DIR_CLOSE
};
