import { BACKTESTER_SERVICE } from "cpz/config/services";
import {
  BASE_EVENT,
  SUB_VALIDATION_EVENT,
  SUB_DELETED_EVENT
} from "cpz/events/types/base";
import schemas from "cpz/events/schemas";
import {
  ERROR_BACKTESTER_EVENT,
  LOG_BACKTESTER_EVENT,
  TASKS_BACKTESTER_FINISHED_EVENT,
  TASKS_BACKTESTER_START_EVENT,
  TASKS_BACKTESTER_STARTED_EVENT,
  TASKS_BACKTESTER_STOP_EVENT,
  TASKS_BACKTESTER_STOPPED_EVENT,
  TRADES_ORDER_EVENT,
  TRADES_POSITION_EVENT
} from "cpz/config/events/types";
import { LOG_TOPIC, TASKS_TOPIC, ERROR_TOPIC } from "cpz/events/topics";

export default {
  serviceName: BACKTESTER_SERVICE,
  events: {
    topics: {
      ERROR_TOPIC,
      TASKS_TOPIC,
      LOG_TOPIC
    },
    types: {
      BASE_EVENT,
      SUB_VALIDATION_EVENT,
      SUB_DELETED_EVENT,
      TASKS_BACKTESTER_START_EVENT,
      TASKS_BACKTESTER_STOP_EVENT,
      TASKS_BACKTESTER_STARTED_EVENT,
      TASKS_BACKTESTER_STOPPED_EVENT,
      TASKS_BACKTESTER_FINISHED_EVENT,
      ERROR_BACKTESTER_EVENT,
      LOG_BACKTESTER_EVENT,
      TRADES_POSITION_EVENT,
      TRADES_ORDER_EVENT
    },
    schemas: {
      [BASE_EVENT]: schemas[BASE_EVENT],
      [TASKS_BACKTESTER_START_EVENT]: schemas[TASKS_BACKTESTER_START_EVENT],
      [TASKS_BACKTESTER_STOP_EVENT]: schemas[TASKS_BACKTESTER_STOP_EVENT],
      [LOG_BACKTESTER_EVENT]: schemas[LOG_BACKTESTER_EVENT],
      [TRADES_POSITION_EVENT]: schemas[TRADES_POSITION_EVENT],
      [TRADES_ORDER_EVENT]: schemas[TRADES_ORDER_EVENT],
      [TASKS_BACKTESTER_STARTED_EVENT]: schemas[TASKS_BACKTESTER_STARTED_EVENT],
      [TASKS_BACKTESTER_STOPPED_EVENT]: schemas[TASKS_BACKTESTER_STOPPED_EVENT],
      [TASKS_BACKTESTER_FINISHED_EVENT]:
        schemas[TASKS_BACKTESTER_FINISHED_EVENT],
      [ERROR_BACKTESTER_EVENT]: schemas[ERROR_BACKTESTER_EVENT]
    }
  }
};
