/**
 * Azure Table Storage - Tables List
 */

const STORAGE_ADVISERS_TABLE = "Advisers"; // Adviser
const STORAGE_BACKTESTS_TABLE = "Backtests"; // Backtester
const STORAGE_BACKTESTERS_TABLE = "Backtesters"; // Backtester
const STORAGE_BACKTESTERITEMS_TABLE = "BacktesterItems"; // Backtester
const STORAGE_BACKTESTERSTRATLOG_TABLE = "BacktesterStratLogs"; // Backtester
const STORAGE_BACKTESTERSIGNALS_TABLE = "BacktesterSignals"; // Backtester
const STORAGE_BACKTESTERORDERS_TABLE = "BacktesterOrders"; // Backtester
const STORAGE_BACKTESTERPOSITIONS_TABLE = "BacktesterPositions"; // Backtester
const STORAGE_CANDLEBATCHERS_TABLE = "Candlebatchers"; // Candlebatcher
const STORAGE_CANDLESCACHED_TABLE = "CandlesCached"; // Candlebatcher / Adviser
const STORAGE_CANDLESTEMP_TABLE = "CandlesTemp"; // Importer
const STORAGE_CANDLESPENDING_TABLE = "CandlesPending"; // Candlebatcher
const STORAGE_CURRENTPRICES_TABLE = "CurrentPrices"; // Current market prices
const STORAGE_EXWATCHERS_TABLE = "Exwatchers"; // Exchange data watcher
const STORAGE_IMPORTERS_TABLE = "Importers"; // Importer
const STORAGE_MARKETWATCHERS_TABLE = "Marketwatchers"; // Marketwatcher
const STORAGE_POSITIONS_TABLE = "Positions"; // Trader
const STORAGE_SIGNALSPENDING_TABLE = "SignalsPending"; // Trader
const STORAGE_TICKSCACHED_TABLE = "TicksCashed"; // Marketwatcher / Adviser
const STORAGE_TRADERS_TABLE = "Traders"; // Trader
const STORAGE_USERROBOTS_TABLE = "UserRobots";

const STORAGE_TASKS_EVENTS_TABLE = "TasksEvents";
const STORAGE_SIGNALS_EVENTS_TABLE = "SignalsEvents";
const STORAGE_ORDERS_EVENTS_TABLE = "OrdersEvents";
const STORAGE_POSITIONS_EVENTS_TABLE = "PositionsEvents";
const STORAGE_LOGS_EVENTS_TABLE = "LogEvents";
const STORAGE_ERRORS_EVENTS_TABLE = "ErrorEvents";

export {
  STORAGE_ADVISERS_TABLE,
  STORAGE_BACKTESTS_TABLE,
  STORAGE_BACKTESTERS_TABLE,
  STORAGE_BACKTESTERITEMS_TABLE,
  STORAGE_BACKTESTERSTRATLOG_TABLE,
  STORAGE_BACKTESTERSIGNALS_TABLE,
  STORAGE_BACKTESTERORDERS_TABLE,
  STORAGE_BACKTESTERPOSITIONS_TABLE,
  STORAGE_CANDLEBATCHERS_TABLE,
  STORAGE_CANDLESCACHED_TABLE,
  STORAGE_CANDLESTEMP_TABLE,
  STORAGE_CANDLESPENDING_TABLE,
  STORAGE_CURRENTPRICES_TABLE,
  STORAGE_IMPORTERS_TABLE,
  STORAGE_MARKETWATCHERS_TABLE,
  STORAGE_POSITIONS_TABLE,
  STORAGE_SIGNALSPENDING_TABLE,
  STORAGE_TICKSCACHED_TABLE,
  STORAGE_TRADERS_TABLE,
  STORAGE_USERROBOTS_TABLE,
  STORAGE_EXWATCHERS_TABLE,
  STORAGE_TASKS_EVENTS_TABLE,
  STORAGE_SIGNALS_EVENTS_TABLE,
  STORAGE_ORDERS_EVENTS_TABLE,
  STORAGE_POSITIONS_EVENTS_TABLE,
  STORAGE_LOGS_EVENTS_TABLE,
  STORAGE_ERRORS_EVENTS_TABLE
};
