const ERROR_ADVISER_ERROR_EVENT = "CPZ.Adviser.Error";
const ERROR_BACKTEST_ERROR_EVENT = "CPZ.Backtest.Error";
const ERROR_BACKTESTER_ERROR_EVENT = "CPZ.Backtester.Error";
const ERROR_CANDLEBATCHER_ERROR_EVENT = "CPZ.Candlebatcher.Error";
const ERROR_CONTROL_ERROR_EVENT = "CPZ.Control.Error";
const ERROR_EXWATCHER_ERROR_EVENT = "CPZ.Exwatcher.Error";
const ERROR_IMPORTER_ERROR_EVENT = "CPZ.Importer.Error";
const ERROR_MARKETWATCHER_ERROR_EVENT = "CPZ.Marketwatcher.Error";
const ERROR_TRADER_ERROR_EVENT = "CPZ.Trader.Error";
const ERROR_USERROBOT_ERROR_EVENT = "CPZ.UserRobot.Error";

export {
  ERROR_ADVISER_ERROR_EVENT,
  ERROR_BACKTEST_ERROR_EVENT,
  ERROR_BACKTESTER_ERROR_EVENT,
  ERROR_CANDLEBATCHER_ERROR_EVENT,
  ERROR_CONTROL_ERROR_EVENT,
  ERROR_EXWATCHER_ERROR_EVENT,
  ERROR_IMPORTER_ERROR_EVENT,
  ERROR_MARKETWATCHER_ERROR_EVENT,
  ERROR_TRADER_ERROR_EVENT,
  ERROR_USERROBOT_ERROR_EVENT
};
