const LOG_ADVISER_LOG_EVENT = "CPZ.Adviser.Log";
const LOG_BACKTEST_LOG_EVENT = "CPZ.Backtest.Log";
const LOG_BACKTESTER_LOG_EVENT = "CPZ.Backtester.Log";
const LOG_CANDLEBATCHER_LOG_EVENT = "CPZ.Candlebatcher.Log";
const LOG_CONTROL_LOG_EVENT = "CPZ.Control.Log";
const LOG_EXWATCHER_LOG_EVENT = "CPZ.Exwatcher.Log";
const LOG_IMPORTER_LOG_EVENT = "CPZ.Importer.Log";
const LOG_MARKETWATCHER_LOG_EVENT = "CPZ.Marketwatcher.Log";
const LOG_TRADER_LOG_EVENT = "CPZ.Trader.Log";
const LOG_USERROBOT_LOG_EVENT = "CPZ.UserRobot.Log";

export {
  LOG_ADVISER_LOG_EVENT,
  LOG_BACKTEST_LOG_EVENT,
  LOG_BACKTESTER_LOG_EVENT,
  LOG_CANDLEBATCHER_LOG_EVENT,
  LOG_CONTROL_LOG_EVENT,
  LOG_EXWATCHER_LOG_EVENT,
  LOG_IMPORTER_LOG_EVENT,
  LOG_MARKETWATCHER_LOG_EVENT,
  LOG_TRADER_LOG_EVENT,
  LOG_USERROBOT_LOG_EVENT
};
