name: Node CI

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
          ENCRYPTION_PWD: e8424bff-4ddf-4e3b-9f6f-2cd9f1d12b39
