const CONTROL_SERVICE = "control";
const MARKETWATCHER_SERVICE = "marketwatcher";
const CANDLEBATCHER_SERVICE = "candlebatcher";
const EXWATCHER_SERVICE = "exwatcher";
const IMPORTER_SERVICE = "importer";
const ADVISER_SERVICE = "adviser";
const TRADER_SERVICE = "trader";
const BACKTESTER_SERVICE = "backtester";
const EVENTS_LOGGER_SERVICE = "eventslogger";
const CONNECTOR_SERVICE = "connector";

export {
  CONTROL_SERVICE,
  MARKETWATCHER_SERVICE,
  CANDLEBATCHER_SERVICE,
  EXWATCHER_SERVICE,
  IMPORTER_SERVICE,
  ADVISER_SERVICE,
  TRADER_SERVICE,
  BACKTESTER_SERVICE,
  EVENTS_LOGGER_SERVICE,
  CONNECTOR_SERVICE
};
